### ISSUE TITLE
How to implement the Summer tileset?

### ISSUE THREAD

**Issue by MatveyK** [kchapelier/wavefunctioncollapse#1]
Hello, awesome job on this port!

I've used the examples you provided and they work perfectly fine, so I've tried to implement the "Summer" tileset from the original repo, but it doesn't seem to work.

Here the gist of the definition that I've made using your example and the original repo xml: [https://gist.github.com/MatveyK/8e04c76120a0e10e0cffa9dac611b8f2](url)

Except that when I try to run the Simple Tiled Model with it and the associated tile files in the /summer folder, I get this message:

(node:11499) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open './data/summer/cliffcorner.png'

Thus my question is: how do you organize the definition file in this case? Because translating the original repo xml to json object doesn't seem to work in this case.

I've seen that in your animated simple tile example you run the summer tileset, I was wondering if you could upload the definition file for it? Or if you could explain the structure of the definition file?

**Comment by kchapelier** [comment]
Hi, thank you ! It seems that the issue is that I haven't implemented support for the 'unique' attribute in the node.js example so it tries to load the wrong file (ie `cliffcorner.png` instead of `cliffcorner 0.png`, `cliffcorner 1.png`, `cliffcorner 2.png` and `cliffcorner 3.png`) whereas it is correctly handled in the browser demo. I'll try to get that done later today.

For reference, all the translated SimpleTiledModel definitions for the browser demo can be seen here : http://www.kchapelier.com/wfc-example/simple-tiled-model-data.js The only difference with your summer definition is that it includes 'weight' attributes on some tiles (and that it doesn't include the 'path' on each tile because of the different image loading process).

**Comment by MatveyK** [comment]
Thanks for the quick answer and for your help!

Another quick question: could you enlighten me as to what the "symmetry" values are meant to represent? I understood that the neighbors list defines the rules for right-left neighbours (as in which tile can be followed by which tile), but the meaning of the symmetry values eludes me.

**Comment by kchapelier** [comment]
https://github.com/kchapelier/wavefunctioncollapse/commit/0e394c5842252dcd330c33ca829fc5f5302b6663

I fixed the node simple-tiled-model example so that it supports `unique` tilesets. It can be tested by just replacing the `require('./data/castle.definition.js');` with `require('./data/summer.definition.js');`.

Regarding the `symmetry` value, you should check this [discussion](https://github.com/mxgmn/WaveFunctionCollapse/issues/3#issuecomment-255586245) on the original repository.

**Comment by MatveyK** [comment]
Thanks a million for the quick reply and help!
