### ISSUE TITLE
TypeError: rng is not a function

### ISSUE THREAD

**Issue by Kiborgik** [kchapelier/wavefunctioncollapse#3]
```
TypeError: rng is not a function
    at SimpleTiledModel.Model.observe (webpack-internal:///./node_modules/wavefunctioncollapse/model.js:102)
    at SimpleTiledModel.Model.singleIteration (webpack-internal:///./node_modules/wavefunctioncollapse/model.js:189)
    at SimpleTiledModel.Model.generate (webpack-internal:///./node_modules/wavefunctioncollapse/model.js:250)
```
I tried using it with Vue

**Comment by kchapelier** [comment]
@Kiborgik Could you provide the code you use to call the function `generate` ?

**Comment by kchapelier** [comment]
@Kiborgik I've looked further into it, and the error must come from your call. The argument you pass to the `generate` function, if any, must be a function acting as a random number generator (see [doc](https://github.com/kchapelier/wavefunctioncollapse#common-methods)). If the argument is undefined / null / falsey, it defaults to `Math.random`, so the only way to trigger this error is by passing an argument which is neither a function nor falsey. I'm guessing you probably have something along the lines of `model.generate(Math.random())` where it should actually be `model.generate(Math.random)`.

Let me know if this helps fixing your issue.

**Comment by Kiborgik** [comment]
Hello, im using code from your example. `finished = model.generate(lcg("test"));`
Maybe problem with my implementation of  lcg(). Thank you for answer.

**Comment by kchapelier** [comment]
@Kiborgik Probably. In my case `lcg(...)` [returns](https://github.com/kchapelier/wavefunctioncollapse/blob/2.0.0/example/lcg.js#L25) a function which act as a random number generator (a linear congruential generator to be precise). If you don't need to be able to have reproducible results, you can pass `Math.random` as argument to the `generate` function otherwise you could look into using the [compute-lcg](https://www.npmjs.com/package/compute-lcg) or the [seedrandom](https://www.npmjs.com/package/seedrandom) packages.

**Comment by Kiborgik** [comment]
Anyway nice work from you. Take care
